"use client";
import { useActionState } from "react";
import type { FinanceActionState } from "@/app/(dashboard)/patients/[id]/finance-actions";
import type { DentalFinding } from "@/lib/odontogram/data";
import type { FinancialSummary, InterventionView, Payment } from "@/lib/finance/data";
import { interventionStatuses, paymentMethodLabels, paymentMethods } from "@/lib/finance/validation";
import { conditionLabels, permanentTeeth } from "@/lib/odontogram/validation";
import type { AppRole } from "@/lib/permissions";

type Props={patientActive:boolean;role:AppRole;summary:FinancialSummary;interventions:InterventionView[];payments:Payment[];findings:DentalFinding[];paymentToken:string;today:string;nowLocal:string;createAction:(s:FinanceActionState,f:FormData)=>Promise<FinanceActionState>;updateAction:(id:string,s:FinanceActionState,f:FormData)=>Promise<FinanceActionState>;cancelAction:(id:string,s:FinanceActionState,f:FormData)=>Promise<FinanceActionState>;recordAction:(s:FinanceActionState,f:FormData)=>Promise<FinanceActionState>;reverseAction:(id:string,s:FinanceActionState,f:FormData)=>Promise<FinanceActionState>};
const initial:FinanceActionState={success:false,message:null,fieldErrors:{}};
const money=new Intl.NumberFormat("fr-MA",{style:"currency",currency:"MAD",minimumFractionDigits:2});
const date=new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeZone:"UTC"});
const dateTime=new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short"});
const input="mt-1 w-full rounded-md border border-[var(--border)] bg-white px-3 py-2 text-sm";

export function PatientFinances(props:Props){
  const received=props.summary.outstanding===0;
  return <section className="mt-6 space-y-6" aria-labelledby="finances-title">
    <div className="rounded-lg border border-[var(--border)] bg-white p-5 sm:p-6">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold text-slate-900" id="finances-title">Interventions et situation financière</h2><p className="mt-1 text-sm text-[var(--muted)]">Montants dérivés des interventions réalisées et paiements reçus.</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${received?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-900"}`}>{received?"Reçu":"À recevoir"}</span></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-3"><Summary label="Total des interventions" value={props.summary.total_due}/><Summary label="Montant reçu" value={props.summary.total_received}/><Summary label="Reste à recevoir" value={props.summary.outstanding}/></div>
      <p className="mt-3 text-xs text-[var(--muted)]">Les paiements sont affectés au compte global du patient, pas artificiellement à une intervention particulière.</p>
    </div>
    <div className="grid gap-6 xl:grid-cols-2">
      <div className="rounded-lg border border-[var(--border)] bg-white p-5 sm:p-6"><h3 className="font-semibold text-slate-900">Interventions</h3><div className="mt-4 space-y-4">{props.interventions.map(item=><InterventionCard key={item.id} item={item} {...props}/>) }{!props.interventions.length?<Empty text="Aucune intervention enregistrée."/>:null}</div>{props.patientActive?<InterventionForm action={props.createAction} findings={props.findings} today={props.today}/>:<ReadOnly/>}</div>
      <div className="rounded-lg border border-[var(--border)] bg-white p-5 sm:p-6"><h3 className="font-semibold text-slate-900">Paiements</h3><div className="mt-4 space-y-3">{props.payments.map(item=><PaymentCard key={item.id} item={item} role={props.role} patientActive={props.patientActive} reverseAction={props.reverseAction.bind(null,item.id)}/>)}{!props.payments.length?<Empty text="Aucun paiement enregistré."/>:null}</div>{props.patientActive&&props.summary.outstanding>0?<PaymentForm key={props.paymentToken} action={props.recordAction} nowLocal={props.nowLocal} token={props.paymentToken}/>:props.patientActive?<p className="mt-5 rounded-md bg-emerald-50 px-4 py-3 text-sm text-emerald-800">Aucun montant à recevoir.</p>:<ReadOnly/>}</div>
    </div>
  </section>;
}
function Summary({label,value}:{label:string;value:number}){return <div className="rounded-md bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-[var(--muted)]">{label}</p><p className="mt-1 text-xl font-bold text-slate-900">{money.format(value)}</p></div>}
function Empty({text}:{text:string}){return <p className="rounded-md bg-slate-50 px-4 py-3 text-sm text-[var(--muted)]">{text}</p>}
function ReadOnly(){return <p className="mt-5 rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">Lecture seule : dossier patient archivé.</p>}

function InterventionCard({item,patientActive,role,findings,today,updateAction,cancelAction}:Props&{item:InterventionView}){
  const [cancelState,cancelFormAction,cancelPending]=useActionState(cancelAction.bind(null,item.id),initial);
  if(item.status==="cancelled"||!patientActive)return <article className="rounded-md border border-slate-200 p-4"><div className="flex justify-between gap-3"><p className="font-medium text-slate-900">{item.nature}</p><span className="text-sm font-semibold">{money.format(item.amount_due)}</span></div><p className="mt-1 text-sm text-[var(--muted)]">{date.format(new Date(`${item.performed_at}T00:00:00Z`))} · {item.status==="cancelled"?"Annulée":item.status==="performed"?"Réalisée":"Planifiée"}</p><p className="mt-1 text-sm">Dents : {item.teeth.join(", ")||"Non précisé"}</p>{item.notes?<p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{item.notes}</p>:null}</article>;
  return <details className="rounded-md border border-slate-200 p-4"><summary className="cursor-pointer"><span className="font-medium text-slate-900">{item.nature}</span><span className="ml-2 text-sm text-[var(--muted)]">{money.format(item.amount_due)} · {item.status==="performed"?"Réalisée":"Planifiée"}</span></summary><InterventionForm action={updateAction.bind(null,item.id)} findings={findings} initialValue={item} today={today}/>{role==="doctor"?<form action={cancelFormAction} className="mt-3" onSubmit={event=>{if(!confirm("Annuler cette intervention ? L’historique sera conservé."))event.preventDefault();}}><Message state={cancelState}/><button className="text-sm font-semibold text-red-700 disabled:opacity-60" disabled={cancelPending} type="submit">Annuler l’intervention</button></form>:null}</details>;
}
function InterventionForm({action,findings,today,initialValue}:{action:Props["createAction"];findings:DentalFinding[];today:string;initialValue?:InterventionView}){
  const [state,formAction,pending]=useActionState(action,initial); return <form action={formAction} className="mt-5 rounded-md border border-dashed border-slate-300 bg-slate-50 p-4"><h4 className="text-sm font-semibold">{initialValue?"Modifier l’intervention":"Nouvelle intervention"}</h4><div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Date" error={state.fieldErrors.performedAt}><input className={input} defaultValue={initialValue?.performed_at??today} name="performedAt" required type="date"/></Field><Field label="Statut" error={state.fieldErrors.status}><select className={input} defaultValue={initialValue?.status??"performed"} name="status">{interventionStatuses.map(s=><option key={s} value={s}>{s==="performed"?"Réalisée":"Planifiée"}</option>)}</select></Field><Field label="Nature" error={state.fieldErrors.nature} wide><input className={input} defaultValue={initialValue?.nature??""} maxLength={160} name="nature" required/></Field><Field label="Prix (MAD)" error={state.fieldErrors.amountDue}><input className={input} defaultValue={initialValue?.amount_due.toFixed(2)??""} inputMode="decimal" name="amountDue" pattern="[0-9]+([.][0-9]{1,2})?" required/></Field><Field label="Notes cliniques" error={state.fieldErrors.notes} wide><textarea className={input} defaultValue={initialValue?.notes??""} maxLength={4000} name="notes" rows={2}/></Field></div><details className="mt-3"><summary className="cursor-pointer text-sm font-medium">Dents concernées</summary><div className="mt-2 flex flex-wrap gap-2">{permanentTeeth.map(tooth=><label className="rounded border border-slate-200 bg-white px-2 py-1 text-xs" key={tooth}><input className="mr-1" defaultChecked={initialValue?.teeth.includes(tooth)} name="teeth" type="checkbox" value={tooth}/>{tooth}</label>)}</div></details>{findings.length?<details className="mt-3"><summary className="cursor-pointer text-sm font-medium">Constatations liées</summary><div className="mt-2 space-y-1">{findings.map(f=><label className="block text-sm" key={f.id}><input className="mr-2" defaultChecked={initialValue?.findingIds.includes(f.id)} name="findingIds" type="checkbox" value={f.id}/>Dent {f.tooth_number} — {conditionLabels[f.condition]}</label>)}</div></details>:null}<Message state={state}/><button className="mt-4 rounded-md bg-[var(--brand)] px-4 py-2 text-sm font-semibold text-white disabled:opacity-60" disabled={pending} type="submit">{pending?"Enregistrement…":initialValue?"Mettre à jour":"Enregistrer"}</button></form>;
}
function PaymentForm({action,nowLocal,token}:{action:Props["recordAction"];nowLocal:string;token:string}){const[state,formAction,pending]=useActionState(action,initial);return <form action={formAction} className="mt-5 rounded-md border border-dashed border-slate-300 bg-slate-50 p-4"><h4 className="text-sm font-semibold">Enregistrer un paiement</h4><input name="idempotencyKey" type="hidden" value={token}/><div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Montant reçu (MAD)" error={state.fieldErrors.amount}><input className={input} inputMode="decimal" name="amount" pattern="[0-9]+([.][0-9]{1,2})?" required/></Field><Field label="Mode" error={state.fieldErrors.method}><select className={input} name="method">{paymentMethods.map(m=><option key={m} value={m}>{paymentMethodLabels[m]}</option>)}</select></Field><Field label="Reçu le" error={state.fieldErrors.receivedAt}><input className={input} defaultValue={nowLocal} name="receivedAt" required type="datetime-local"/></Field><Field label="Référence" error={state.fieldErrors.reference}><input className={input} maxLength={160} name="reference"/></Field><Field label="Note" error={state.fieldErrors.notes} wide><textarea className={input} maxLength={2000} name="notes" rows={2}/></Field></div><Message state={state}/><button className="mt-4 rounded-md bg-[var(--brand)] px-4 py-2 text-sm font-semibold text-white disabled:opacity-60" disabled={pending} type="submit">{pending?"Enregistrement…":"Enregistrer le paiement"}</button></form>}
function PaymentCard({item,role,patientActive,reverseAction}:{item:Payment;role:AppRole;patientActive:boolean;reverseAction:(s:FinanceActionState,f:FormData)=>Promise<FinanceActionState>}){const[state,formAction,pending]=useActionState(reverseAction,initial);return <article className="rounded-md border border-slate-200 p-4"><div className="flex justify-between gap-3"><p className="font-semibold">{money.format(item.amount)}</p><span className={`text-xs font-semibold ${item.status==="received"?"text-emerald-700":"text-slate-500"}`}>{item.status==="received"?"Reçu":"Paiement annulé"}</span></div><p className="mt-1 text-sm text-[var(--muted)]">{dateTime.format(new Date(item.received_at))} · {paymentMethodLabels[item.method]}</p>{item.reference?<p className="mt-1 text-sm">Référence : {item.reference}</p>:null}{item.notes?<p className="mt-2 whitespace-pre-wrap text-sm">{item.notes}</p>:null}{item.status==="reversed"?<p className="mt-2 text-sm text-slate-600">Motif : {item.reversal_reason}</p>:null}{role==="doctor"&&patientActive&&item.status==="received"?<form action={formAction} className="mt-3" onSubmit={event=>{if(!confirm("Annuler ce paiement ? Le solde sera recalculé."))event.preventDefault();}}><label className="text-sm font-medium">Motif<input className={input} maxLength={500} minLength={5} name="reason" required/></label><Message state={state}/><button className="mt-2 text-sm font-semibold text-red-700 disabled:opacity-60" disabled={pending} type="submit">Annuler le paiement</button></form>:null}</article>}
function Field({children,label,error,wide=false}:{children:React.ReactNode;label:string;error?:string;wide?:boolean}){return <label className={`text-sm font-medium text-slate-700 ${wide?"sm:col-span-2":""}`}>{label}{children}{error?<span className="mt-1 block text-sm text-red-700">{error}</span>:null}</label>}
function Message({state}:{state:FinanceActionState}){return state.message?<p aria-live="polite" className={`mt-3 text-sm ${state.success?"text-emerald-700":"text-red-700"}`}>{state.message}</p>:null}
