import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import path from "node:path";
import test from "node:test";
const migrationPath=path.join(process.cwd(),"supabase/migrations/20260912120000_appointments_reminders.sql");

test("appointment tables are RLS protected and RPC-only for mutations",async()=>{const sql=await readFile(migrationPath,"utf8");for(const table of ["appointments","appointment_revisions","appointment_reminders"])assert.match(sql,new RegExp(`alter table public\\.${table} enable row level security`,`i`));assert.doesNotMatch(sql,/grant (insert|update|delete) on table public\.(appointments|appointment_revisions|appointment_reminders)/i);assert.doesNotMatch(sql,/create policy .* (insert|update|delete|all)/i);});
test("schedule uses timestamptz, transactional overlap exclusion and idempotency",async()=>{const sql=await readFile(migrationPath,"utf8");assert.match(sql,/starts_at timestamptz not null/i);assert.match(sql,/exclude using gist \(tstzrange\(starts_at,ends_at,'\[\)'\) with &&\) where \(status='scheduled'\)/i);assert.match(sql,/idempotency_key uuid not null unique/i);assert.match(sql,/exception when exclusion_violation/i);});
test("security definer RPCs lock search path and enforce trusted actors and patient state",async()=>{const sql=await readFile(migrationPath,"utf8");const functions=[...sql.matchAll(/create function (public\.(?:create|update|cancel|set|mark|get)[^(]+)[\s\S]*?\$\$;/gi)];assert.ok(functions.length>=6);for(const fn of functions)assert.match(fn[0],/security definer[\s\S]*set search_path=''/i,fn[1]);assert.match(sql,/actor uuid:=auth\.uid\(\)/gi);assert.match(sql,/p\.is_active/gi);});
test("history and generic audit avoid sensitive appointment and reminder content",async()=>{const sql=await readFile(migrationPath,"utf8");assert.match(sql,/insert into public\.appointment_revisions/i);const metadata=[...sql.matchAll(/jsonb_build_object\(([^)]*)\)/gi)].map(match=>match[1]).join("\n");assert.doesNotMatch(metadata,/notes|title|purpose|phone|message/i);assert.doesNotMatch(sql,/delete from public\.(appointments|appointment_revisions|appointment_reminders)/i);});
test("reminders are derived, manual acknowledgements and exclude obsolete appointments",async()=>{const sql=await readFile(migrationPath,"utf8");assert.match(sql,/starts_at-interval '24 hours'/i);assert.match(sql,/starts_at-interval '2 hours'/i);assert.match(sql,/a\.status='scheduled'/i);assert.match(sql,/a\.starts_at>reference_time/i);assert.match(sql,/on conflict do nothing/i);assert.doesNotMatch(sql,/whatsapp.*api|message_body|send_message/i);});
