"use server";
import {revalidatePath} from "next/cache";
import {requirePermission} from "@/lib/auth/server";
import {isPatientId} from "@/lib/patients/validation";
import {isPrescriptionId,validatePrescriptionForm,validateVoidReason,type PrescriptionField} from "@/lib/prescriptions/validation";
import {createClient} from "@/lib/supabase/server";
export type PrescriptionActionState={success:boolean;message:string|null;fieldErrors:Partial<Record<PrescriptionField|"reason",string>>};
const failure=(message:string,fieldErrors:PrescriptionActionState["fieldErrors"]={}):PrescriptionActionState=>({success:false,message,fieldErrors});
export async function createPrescriptionAction(patientId:string,_state:PrescriptionActionState,formData:FormData):Promise<PrescriptionActionState>{await requirePermission("prescriptions.create");if(!isPatientId(patientId))return failure("Dossier patient invalide.");const validation=validatePrescriptionForm(formData);if(!validation.success)return failure(validation.message,validation.fieldErrors);const supabase=await createClient();const {error}=await supabase.rpc("create_prescription",{target_patient_id:patientId,target_notes:validation.data.notes,target_items:validation.data.items,target_idempotency_key:validation.data.idempotencyKey});if(error)return failure(error.code==="22023"?"Le patient ou le contenu de l’ordonnance n’est pas valide.":error.code==="23505"?"Cette demande a déjà été utilisée avec un contenu différent. Rechargez la page et réessayez.":"L’ordonnance n’a pas pu être créée.");revalidatePath(`/patients/${patientId}`);return {success:true,message:"Ordonnance émise. Son contenu est désormais immuable.",fieldErrors:{}};}
export async function voidPrescriptionAction(patientId:string,prescriptionId:string,_state:PrescriptionActionState,formData:FormData):Promise<PrescriptionActionState>{await requirePermission("prescriptions.void");if(!isPatientId(patientId)||!isPrescriptionId(prescriptionId))return failure("Ordonnance invalide.");const reason=validateVoidReason(formData.get("reason"));if(!reason)return failure("Le motif doit contenir entre 5 et 500 caractères.",{reason:"Motif requis."});const supabase=await createClient();const {data,error}=await supabase.rpc("void_prescription",{target_patient_id:patientId,target_prescription_id:prescriptionId,target_reason:reason});if(error||!data)return failure("Cette ordonnance ne peut pas être annulée.");revalidatePath(`/patients/${patientId}`);revalidatePath(`/patients/${patientId}/prescriptions/${prescriptionId}/print`);return {success:true,message:"Ordonnance annulée; son contenu reste conservé.",fieldErrors:{}};}
