"use client";

import {useActionState} from "react";
import type {AppointmentActionState} from "@/app/(dashboard)/appointments/actions";
import type {AppointmentListItem,PatientOption,ReminderItem} from "@/lib/appointments/data";
import {clinicDateValue,clinicTimeValue,formatClinicDate,formatClinicTime} from "@/lib/appointments/validation";

type Props={appointments:AppointmentListItem[];patients:PatientOption[];reminders:ReminderItem[];selectedDate:string;defaultPatientId?:string;now:string;token:string;createAction:(s:AppointmentActionState,f:FormData)=>Promise<AppointmentActionState>;updateAction:(id:string,s:AppointmentActionState,f:FormData)=>Promise<AppointmentActionState>;cancelAction:(id:string,patientId:string,s:AppointmentActionState,f:FormData)=>Promise<AppointmentActionState>;statusAction:(id:string,patientId:string,status:"completed"|"no_show")=>Promise<void>;reminderAction:(id:string,patientId:string,type:"day_before"|"two_hours_before")=>Promise<void>};
const initial:AppointmentActionState={success:false,message:null,fieldErrors:{}};
const input="mt-1 w-full rounded-md border border-[var(--border)] bg-white px-3 py-2 text-sm";
const statusLabels={scheduled:"Planifié",completed:"Terminé",cancelled:"Annulé",no_show:"Absent"};
const reminderLabels={day_before:"J-1",two_hours_before:"H-2"};

export function Schedule(props:Props){
  return <div className="mt-6 grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_360px]">
    <div className="space-y-5">
      {props.reminders.length?<section aria-labelledby="reminders-title" className="rounded-lg border border-amber-200 bg-amber-50 p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold text-amber-950" id="reminders-title">Rappels à traiter</h2><p className="mt-1 text-sm text-amber-900">Ouverture manuelle de WhatsApp; confirmez ensuite le traitement séparément.</p></div><span aria-label={`${props.reminders.length} rappels à traiter`} className="rounded-full bg-amber-200 px-3 py-1 text-sm font-bold text-amber-950">{props.reminders.length}</span></div><div className="mt-4 grid gap-3">{props.reminders.map(item=><ReminderCard item={item} key={`${item.appointmentId}-${item.type}`} markAction={props.reminderAction}/>)}</div></section>:null}
      <section aria-labelledby="day-title" className="overflow-hidden rounded-lg border border-[var(--border)] bg-white"><div className="border-b border-[var(--border)] px-5 py-4"><h2 className="font-semibold capitalize text-slate-900" id="day-title">{formatClinicDate(`${props.selectedDate}T12:00:00Z`)}</h2><p className="mt-1 text-sm text-[var(--muted)]">{props.appointments.length} rendez-vous · heure du cabinet (Casablanca)</p></div><div className="divide-y divide-[var(--border)]">{props.appointments.map(item=><AppointmentCard item={item} key={item.id} {...props}/>) }{!props.appointments.length?<p className="px-5 py-12 text-center text-sm text-[var(--muted)]">Aucun rendez-vous pour cette journée.</p>:null}</div></section>
    </div>
    <AppointmentForm action={props.createAction} date={props.selectedDate} defaultPatientId={props.defaultPatientId} patients={props.patients} token={props.token}/>
  </div>;
}

function ReminderCard({item,markAction}:{item:ReminderItem;markAction:Props["reminderAction"]}){return <article className="rounded-md border border-amber-200 bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-slate-900">{item.patientName}</p><p className="mt-1 text-sm text-slate-600">{reminderLabels[item.type]} · {formatClinicDate(item.startsAt)} à {formatClinicTime(item.startsAt)}</p></div><span className="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-bold text-amber-900">À traiter</span></div><div className="mt-3 flex flex-wrap gap-2">{item.whatsappUrl?<a className="rounded-md bg-[#128c7e] px-3 py-2 text-sm font-semibold text-white hover:bg-[#0d7166]" href={item.whatsappUrl} rel="noopener noreferrer" target="_blank">Ouvrir WhatsApp</a>:<span className="rounded-md bg-slate-100 px-3 py-2 text-sm text-slate-600">Téléphone incompatible</span>}<form action={markAction.bind(null,item.appointmentId,item.patientId,item.type)}><button className="rounded-md border border-amber-300 bg-white px-3 py-2 text-sm font-semibold text-amber-950" type="submit">Marquer comme traité</button></form></div><p className="mt-2 text-xs text-amber-900">Ouvrir WhatsApp ne confirme pas l’envoi.</p></article>}

function AppointmentCard({item,now,patients,updateAction,cancelAction,statusAction,token}:Props&{item:AppointmentListItem}){
  const patient=item.patient?`${item.patient.first_name} ${item.patient.last_name}`:"Patient";const future=new Date(item.starts_at)>new Date(now);const editable=item.status==="scheduled"&&future;
  return <article className="grid gap-3 px-5 py-4 sm:grid-cols-[92px_minmax(0,1fr)]"><div><p className="text-xl font-bold text-[var(--brand-strong)]">{formatClinicTime(item.starts_at)}</p><p className="text-xs text-[var(--muted)]">jusqu’à {formatClinicTime(item.ends_at)}</p></div><div><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-semibold text-slate-900">{patient}</p><p className="mt-0.5 text-sm text-slate-700">{item.title}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700">{statusLabels[item.status]}</span></div>{item.purpose?<p className="mt-2 text-sm text-slate-600">{item.purpose}</p>:null}{item.notes?<p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{item.notes}</p>:null}{item.cancellation_reason?<p className="mt-2 text-sm text-red-700">Motif d’annulation : {item.cancellation_reason}</p>:null}{item.status==="scheduled"?<div className="mt-3 flex flex-wrap gap-3">{!future?<><form action={statusAction.bind(null,item.id,item.patient_id,"completed")}><button className="text-sm font-semibold text-emerald-700">Marquer terminé</button></form><form action={statusAction.bind(null,item.id,item.patient_id,"no_show")}><button className="text-sm font-semibold text-amber-800">Marquer absent</button></form></>:null}<CancelForm action={cancelAction.bind(null,item.id,item.patient_id)}/></div>:null}{editable?<details className="mt-3 rounded-md bg-slate-50 p-3"><summary className="cursor-pointer text-sm font-semibold text-[var(--brand-strong)]">Modifier le rendez-vous</summary><AppointmentForm action={updateAction.bind(null,item.id)} compact date={clinicDateValue(new Date(item.starts_at))} initial={item} patients={patients} token={token}/></details>:null}</div></article>;
}

function AppointmentForm({action,date,patients,token,initial:appointment,compact=false,defaultPatientId}:{action:Props["createAction"];date:string;patients:PatientOption[];token:string;initial?:AppointmentListItem;compact?:boolean;defaultPatientId?:string}){const[state,formAction,pending]=useActionState(action,initial);return <form action={formAction} className={compact?"mt-4":"sticky top-24 rounded-lg border border-[var(--border)] bg-white p-5"}><h2 className="font-semibold text-slate-900">{appointment?"Modifier":"Nouveau rendez-vous"}</h2><p className="mt-1 text-xs text-[var(--muted)]">Toutes les heures sont interprétées à Casablanca.</p><input name="idempotencyKey" type="hidden" value={appointment?.idempotency_key??token}/><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-1"><Field error={state.fieldErrors.patientId} label="Patient"><select className={input} defaultValue={appointment?.patient_id??defaultPatientId??""} disabled={Boolean(appointment)} name="patientId" required><option disabled value="">Sélectionner…</option>{patients.map(patient=><option key={patient.id} value={patient.id}>{patient.last_name} {patient.first_name}</option>)}</select>{appointment?<input name="patientId" type="hidden" value={appointment.patient_id}/>:null}</Field><Field error={state.fieldErrors.title} label="Titre"><input className={input} defaultValue={appointment?.title??""} maxLength={160} name="title" required/></Field><Field error={state.fieldErrors.purpose} label="Motif"><input className={input} defaultValue={appointment?.purpose??""} maxLength={500} name="purpose"/></Field><Field error={state.fieldErrors.date} label="Date"><input className={input} defaultValue={appointment?clinicDateValue(new Date(appointment.starts_at)):date} name="date" required type="date"/></Field><Field error={state.fieldErrors.startTime} label="Début"><input className={input} defaultValue={appointment?clinicTimeValue(new Date(appointment.starts_at)):"09:00"} name="startTime" required type="time"/></Field><Field error={state.fieldErrors.endTime} label="Fin"><input className={input} defaultValue={appointment?clinicTimeValue(new Date(appointment.ends_at)):"09:30"} name="endTime" required type="time"/></Field><Field error={state.fieldErrors.notes} label="Notes"><textarea className={input} defaultValue={appointment?.notes??""} maxLength={4000} name="notes" rows={2}/></Field></div>{state.message?<p aria-live="polite" className={`mt-3 text-sm ${state.success?"text-emerald-700":"text-red-700"}`}>{state.message}</p>:null}<button className="mt-4 w-full rounded-md bg-[var(--brand)] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60" disabled={pending||!patients.length} type="submit">{pending?"Enregistrement…":appointment?"Enregistrer les modifications":"Créer le rendez-vous"}</button></form>}
function CancelForm({action}:{action:(s:AppointmentActionState,f:FormData)=>Promise<AppointmentActionState>}){const[state,formAction,pending]=useActionState(action,initial);return <details><summary className="cursor-pointer text-sm font-semibold text-red-700">Annuler</summary><form action={formAction} className="mt-2 flex flex-wrap items-end gap-2" onSubmit={event=>{if(!confirm("Annuler ce rendez-vous ? Son historique sera conservé."))event.preventDefault();}}><label className="text-xs font-medium text-slate-700">Motif<input className="ml-2 rounded-md border border-[var(--border)] px-2 py-1.5 text-sm" maxLength={500} minLength={5} name="reason" required/></label><button className="rounded-md border border-red-200 px-2 py-1.5 text-sm font-semibold text-red-700 disabled:opacity-60" disabled={pending}>Confirmer</button>{state.message?<p aria-live="polite" className="w-full text-xs text-red-700">{state.message}</p>:null}</form></details>}
function Field({children,label,error}:{children:React.ReactNode;label:string;error?:string}){return <label className="text-sm font-medium text-slate-700">{label}{children}{error?<span className="mt-1 block text-xs text-red-700">{error}</span>:null}</label>}
